#Sonar organization (required)
sonar.organization=aitzolw
#sonar project Key (required)
sonar.projectKey=aitzolw_rideszuzenduta
#Sonar projectName. The name that appears on a Sonar
dashboard (required)
sonar.projectName=aitzolw_rideszuzenduta
#Maven version. (required)
sonar.projectVersion=0.0.1
#Path with java code (required)
#Helbide erlatiboa
sonar.sources=src
sonar.test=src/test/java
#All paths that contain test (optional)
tests=src
#Paths where the binaries of the project are located
(required)
binaries=bin
sonar.java.binaries=bin
# The project languaje (java for defect)
sonar.language=java
sonar.host.url=https://sonarcloud.io
sonar.dynamicAnalysis=reuseReports
sonar.token=8fb45a724efe521e1a18b6a6dbbdb1053190e695