
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BLFacade", targetNamespace = "http://businessLogic/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BLFacade {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<service.Erreserba>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getReservedRidesByDriver", targetNamespace = "http://businessLogic/", className = "service.GetReservedRidesByDriver")
    @ResponseWrapper(localName = "getReservedRidesByDriverResponse", targetNamespace = "http://businessLogic/", className = "service.GetReservedRidesByDriverResponse")
    @Action(input = "http://businessLogic/BLFacade/getReservedRidesByDriverRequest", output = "http://businessLogic/BLFacade/getReservedRidesByDriverResponse")
    public List<Erreserba> getReservedRidesByDriver(
        @WebParam(name = "arg0", targetNamespace = "")
        Driver arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "erreserbaDeuseztatu", targetNamespace = "http://businessLogic/", className = "service.ErreserbaDeuseztatu")
    @ResponseWrapper(localName = "erreserbaDeuseztatuResponse", targetNamespace = "http://businessLogic/", className = "service.ErreserbaDeuseztatuResponse")
    @Action(input = "http://businessLogic/BLFacade/erreserbaDeuseztatuRequest", output = "http://businessLogic/BLFacade/erreserbaDeuseztatuResponse")
    public void erreserbaDeuseztatu(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "erabiltzaileaEzabatu", targetNamespace = "http://businessLogic/", className = "service.ErabiltzaileaEzabatu")
    @ResponseWrapper(localName = "erabiltzaileaEzabatuResponse", targetNamespace = "http://businessLogic/", className = "service.ErabiltzaileaEzabatuResponse")
    @Action(input = "http://businessLogic/BLFacade/erabiltzaileaEzabatuRequest", output = "http://businessLogic/BLFacade/erabiltzaileaEzabatuResponse")
    public void erabiltzaileaEzabatu(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<service.Erreklamazioa>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "erreklamazioaErakutsiAdmin", targetNamespace = "http://businessLogic/", className = "service.ErreklamazioaErakutsiAdmin")
    @ResponseWrapper(localName = "erreklamazioaErakutsiAdminResponse", targetNamespace = "http://businessLogic/", className = "service.ErreklamazioaErakutsiAdminResponse")
    @Action(input = "http://businessLogic/BLFacade/erreklamazioaErakutsiAdminRequest", output = "http://businessLogic/BLFacade/erreklamazioaErakutsiAdminResponse")
    public List<Erreklamazioa> erreklamazioaErakutsiAdmin(
        @WebParam(name = "arg0", targetNamespace = "")
        Admin arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<service.Erreklamazioa>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "erreklamazioaErakutsiBidaiari", targetNamespace = "http://businessLogic/", className = "service.ErreklamazioaErakutsiBidaiari")
    @ResponseWrapper(localName = "erreklamazioaErakutsiBidaiariResponse", targetNamespace = "http://businessLogic/", className = "service.ErreklamazioaErakutsiBidaiariResponse")
    @Action(input = "http://businessLogic/BLFacade/erreklamazioaErakutsiBidaiariRequest", output = "http://businessLogic/BLFacade/erreklamazioaErakutsiBidaiariResponse")
    public List<Erreklamazioa> erreklamazioaErakutsiBidaiari(
        @WebParam(name = "arg0", targetNamespace = "")
        Bidaiaria arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns service.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "erabiltzaileaBilatu", targetNamespace = "http://businessLogic/", className = "service.ErabiltzaileaBilatu")
    @ResponseWrapper(localName = "erabiltzaileaBilatuResponse", targetNamespace = "http://businessLogic/", className = "service.ErabiltzaileaBilatuResponse")
    @Action(input = "http://businessLogic/BLFacade/erabiltzaileaBilatuRequest", output = "http://businessLogic/BLFacade/erabiltzaileaBilatuResponse")
    public User erabiltzaileaBilatu(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<service.Erreklamazioa>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "erreklamazioaErakutsiGidari", targetNamespace = "http://businessLogic/", className = "service.ErreklamazioaErakutsiGidari")
    @ResponseWrapper(localName = "erreklamazioaErakutsiGidariResponse", targetNamespace = "http://businessLogic/", className = "service.ErreklamazioaErakutsiGidariResponse")
    @Action(input = "http://businessLogic/BLFacade/erreklamazioaErakutsiGidariRequest", output = "http://businessLogic/BLFacade/erreklamazioaErakutsiGidariResponse")
    public List<Erreklamazioa> erreklamazioaErakutsiGidari(
        @WebParam(name = "arg0", targetNamespace = "")
        Driver arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "erreserbaBaloratuDa", targetNamespace = "http://businessLogic/", className = "service.ErreserbaBaloratuDa")
    @ResponseWrapper(localName = "erreserbaBaloratuDaResponse", targetNamespace = "http://businessLogic/", className = "service.ErreserbaBaloratuDaResponse")
    @Action(input = "http://businessLogic/BLFacade/erreserbaBaloratuDaRequest", output = "http://businessLogic/BLFacade/erreserbaBaloratuDaResponse")
    public void erreserbaBaloratuDa(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<service.Mugimendua>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getErabiltzailearenMugimenduak", targetNamespace = "http://businessLogic/", className = "service.GetErabiltzailearenMugimenduak")
    @ResponseWrapper(localName = "getErabiltzailearenMugimenduakResponse", targetNamespace = "http://businessLogic/", className = "service.GetErabiltzailearenMugimenduakResponse")
    @Action(input = "http://businessLogic/BLFacade/getErabiltzailearenMugimenduakRequest", output = "http://businessLogic/BLFacade/getErabiltzailearenMugimenduakResponse")
    public List<Mugimendua> getErabiltzailearenMugimenduak(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "bidaiariaBaloratuDa", targetNamespace = "http://businessLogic/", className = "service.BidaiariaBaloratuDa")
    @ResponseWrapper(localName = "bidaiariaBaloratuDaResponse", targetNamespace = "http://businessLogic/", className = "service.BidaiariaBaloratuDaResponse")
    @Action(input = "http://businessLogic/BLFacade/bidaiariaBaloratuDaRequest", output = "http://businessLogic/BLFacade/bidaiariaBaloratuDaResponse")
    public void bidaiariaBaloratuDa(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<service.Ride>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBaloratuGabekoBidaiaAmaituak", targetNamespace = "http://businessLogic/", className = "service.GetBaloratuGabekoBidaiaAmaituak")
    @ResponseWrapper(localName = "getBaloratuGabekoBidaiaAmaituakResponse", targetNamespace = "http://businessLogic/", className = "service.GetBaloratuGabekoBidaiaAmaituakResponse")
    @Action(input = "http://businessLogic/BLFacade/getBaloratuGabekoBidaiaAmaituakRequest", output = "http://businessLogic/BLFacade/getBaloratuGabekoBidaiaAmaituakResponse")
    public List<Ride> getBaloratuGabekoBidaiaAmaituak(
        @WebParam(name = "arg0", targetNamespace = "")
        Driver arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<service.Erreserba>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBidaiarenErreserbak", targetNamespace = "http://businessLogic/", className = "service.GetBidaiarenErreserbak")
    @ResponseWrapper(localName = "getBidaiarenErreserbakResponse", targetNamespace = "http://businessLogic/", className = "service.GetBidaiarenErreserbakResponse")
    @Action(input = "http://businessLogic/BLFacade/getBidaiarenErreserbakRequest", output = "http://businessLogic/BLFacade/getBidaiarenErreserbakResponse")
    public List<Erreserba> getBidaiarenErreserbak(
        @WebParam(name = "arg0", targetNamespace = "")
        Ride arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<service.Erreserba>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBaloratuGabekoErreserbak", targetNamespace = "http://businessLogic/", className = "service.GetBaloratuGabekoErreserbak")
    @ResponseWrapper(localName = "getBaloratuGabekoErreserbakResponse", targetNamespace = "http://businessLogic/", className = "service.GetBaloratuGabekoErreserbakResponse")
    @Action(input = "http://businessLogic/BLFacade/getBaloratuGabekoErreserbakRequest", output = "http://businessLogic/BLFacade/getBaloratuGabekoErreserbakResponse")
    public List<Erreserba> getBaloratuGabekoErreserbak(
        @WebParam(name = "arg0", targetNamespace = "")
        Bidaiaria arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<service.Erreserba>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBidaiariarenErreserbak", targetNamespace = "http://businessLogic/", className = "service.GetBidaiariarenErreserbak")
    @ResponseWrapper(localName = "getBidaiariarenErreserbakResponse", targetNamespace = "http://businessLogic/", className = "service.GetBidaiariarenErreserbakResponse")
    @Action(input = "http://businessLogic/BLFacade/getBidaiariarenErreserbakRequest", output = "http://businessLogic/BLFacade/getBidaiariarenErreserbakResponse")
    public List<Erreserba> getBidaiariarenErreserbak(
        @WebParam(name = "arg0", targetNamespace = "")
        Bidaiaria arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns service.Admin
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "erabiltzaileaBilatuAdmin", targetNamespace = "http://businessLogic/", className = "service.ErabiltzaileaBilatuAdmin")
    @ResponseWrapper(localName = "erabiltzaileaBilatuAdminResponse", targetNamespace = "http://businessLogic/", className = "service.ErabiltzaileaBilatuAdminResponse")
    @Action(input = "http://businessLogic/BLFacade/erabiltzaileaBilatuAdminRequest", output = "http://businessLogic/BLFacade/erabiltzaileaBilatuAdminResponse")
    public Admin erabiltzaileaBilatuAdmin(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDestinationCities", targetNamespace = "http://businessLogic/", className = "service.GetDestinationCities")
    @ResponseWrapper(localName = "getDestinationCitiesResponse", targetNamespace = "http://businessLogic/", className = "service.GetDestinationCitiesResponse")
    @Action(input = "http://businessLogic/BLFacade/getDestinationCitiesRequest", output = "http://businessLogic/BLFacade/getDestinationCitiesResponse")
    public List<String> getDestinationCities(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<javax.xml.datatype.XMLGregorianCalendar>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getThisMonthDatesWithRides", targetNamespace = "http://businessLogic/", className = "service.GetThisMonthDatesWithRides")
    @ResponseWrapper(localName = "getThisMonthDatesWithRidesResponse", targetNamespace = "http://businessLogic/", className = "service.GetThisMonthDatesWithRidesResponse")
    @Action(input = "http://businessLogic/BLFacade/getThisMonthDatesWithRidesRequest", output = "http://businessLogic/BLFacade/getThisMonthDatesWithRidesResponse")
    public List<XMLGregorianCalendar> getThisMonthDatesWithRides(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        XMLGregorianCalendar arg2);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDepartCities", targetNamespace = "http://businessLogic/", className = "service.GetDepartCities")
    @ResponseWrapper(localName = "getDepartCitiesResponse", targetNamespace = "http://businessLogic/", className = "service.GetDepartCitiesResponse")
    @Action(input = "http://businessLogic/BLFacade/getDepartCitiesRequest", output = "http://businessLogic/BLFacade/getDepartCitiesResponse")
    public List<String> getDepartCities();

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns service.Ride
     * @throws RideMustBeLaterThanTodayException_Exception
     * @throws RideAlreadyExistException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createRide", targetNamespace = "http://businessLogic/", className = "service.CreateRide")
    @ResponseWrapper(localName = "createRideResponse", targetNamespace = "http://businessLogic/", className = "service.CreateRideResponse")
    @Action(input = "http://businessLogic/BLFacade/createRideRequest", output = "http://businessLogic/BLFacade/createRideResponse", fault = {
        @FaultAction(className = RideMustBeLaterThanTodayException_Exception.class, value = "http://businessLogic/BLFacade/createRide/Fault/RideMustBeLaterThanTodayException"),
        @FaultAction(className = RideAlreadyExistException_Exception.class, value = "http://businessLogic/BLFacade/createRide/Fault/RideAlreadyExistException")
    })
    public Ride createRide(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        XMLGregorianCalendar arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        float arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5)
        throws RideAlreadyExistException_Exception, RideMustBeLaterThanTodayException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<service.Ride>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRides", targetNamespace = "http://businessLogic/", className = "service.GetRides")
    @ResponseWrapper(localName = "getRidesResponse", targetNamespace = "http://businessLogic/", className = "service.GetRidesResponse")
    @Action(input = "http://businessLogic/BLFacade/getRidesRequest", output = "http://businessLogic/BLFacade/getRidesResponse")
    public List<Ride> getRides(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        XMLGregorianCalendar arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "diruaSartu", targetNamespace = "http://businessLogic/", className = "service.DiruaSartu")
    @ResponseWrapper(localName = "diruaSartuResponse", targetNamespace = "http://businessLogic/", className = "service.DiruaSartuResponse")
    @Action(input = "http://businessLogic/BLFacade/diruaSartuRequest", output = "http://businessLogic/BLFacade/diruaSartuResponse")
    public void diruaSartu(
        @WebParam(name = "arg0", targetNamespace = "")
        float arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Bidaiaria arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg6
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "erregistratu", targetNamespace = "http://businessLogic/", className = "service.Erregistratu")
    @ResponseWrapper(localName = "erregistratuResponse", targetNamespace = "http://businessLogic/", className = "service.ErregistratuResponse")
    @Action(input = "http://businessLogic/BLFacade/erregistratuRequest", output = "http://businessLogic/BLFacade/erregistratuResponse")
    public boolean erregistratu(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        XMLGregorianCalendar arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "erreserbaEgin", targetNamespace = "http://businessLogic/", className = "service.ErreserbaEgin")
    @ResponseWrapper(localName = "erreserbaEginResponse", targetNamespace = "http://businessLogic/", className = "service.ErreserbaEginResponse")
    @Action(input = "http://businessLogic/BLFacade/erreserbaEginRequest", output = "http://businessLogic/BLFacade/erreserbaEginResponse")
    public void erreserbaEgin(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Bidaiaria arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "erreserbaOnartu", targetNamespace = "http://businessLogic/", className = "service.ErreserbaOnartu")
    @ResponseWrapper(localName = "erreserbaOnartuResponse", targetNamespace = "http://businessLogic/", className = "service.ErreserbaOnartuResponse")
    @Action(input = "http://businessLogic/BLFacade/erreserbaOnartuRequest", output = "http://businessLogic/BLFacade/erreserbaOnartuResponse")
    public void erreserbaOnartu(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Driver arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "diruaAtera", targetNamespace = "http://businessLogic/", className = "service.DiruaAtera")
    @ResponseWrapper(localName = "diruaAteraResponse", targetNamespace = "http://businessLogic/", className = "service.DiruaAteraResponse")
    @Action(input = "http://businessLogic/BLFacade/diruaAteraRequest", output = "http://businessLogic/BLFacade/diruaAteraResponse")
    public void diruaAtera(
        @WebParam(name = "arg0", targetNamespace = "")
        float arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Driver arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saioaHasiAdmin", targetNamespace = "http://businessLogic/", className = "service.SaioaHasiAdmin")
    @ResponseWrapper(localName = "saioaHasiAdminResponse", targetNamespace = "http://businessLogic/", className = "service.SaioaHasiAdminResponse")
    @Action(input = "http://businessLogic/BLFacade/saioaHasiAdminRequest", output = "http://businessLogic/BLFacade/saioaHasiAdminResponse")
    public boolean saioaHasiAdmin(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saioaHasi", targetNamespace = "http://businessLogic/", className = "service.SaioaHasi")
    @ResponseWrapper(localName = "saioaHasiResponse", targetNamespace = "http://businessLogic/", className = "service.SaioaHasiResponse")
    @Action(input = "http://businessLogic/BLFacade/saioaHasiRequest", output = "http://businessLogic/BLFacade/saioaHasiResponse")
    public boolean saioaHasi(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "initializeBD", targetNamespace = "http://businessLogic/", className = "service.InitializeBD")
    @ResponseWrapper(localName = "initializeBDResponse", targetNamespace = "http://businessLogic/", className = "service.InitializeBDResponse")
    @Action(input = "http://businessLogic/BLFacade/initializeBDRequest", output = "http://businessLogic/BLFacade/initializeBDResponse")
    public void initializeBD();

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getnPlaces", targetNamespace = "http://businessLogic/", className = "service.GetnPlaces")
    @ResponseWrapper(localName = "getnPlacesResponse", targetNamespace = "http://businessLogic/", className = "service.GetnPlacesResponse")
    @Action(input = "http://businessLogic/BLFacade/getnPlacesRequest", output = "http://businessLogic/BLFacade/getnPlacesResponse")
    public int getnPlaces(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<service.Balorazioa>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "balorazioaErakutsi", targetNamespace = "http://businessLogic/", className = "service.BalorazioaErakutsi")
    @ResponseWrapper(localName = "balorazioaErakutsiResponse", targetNamespace = "http://businessLogic/", className = "service.BalorazioaErakutsiResponse")
    @Action(input = "http://businessLogic/BLFacade/balorazioaErakutsiRequest", output = "http://businessLogic/BLFacade/balorazioaErakutsiResponse")
    public List<Balorazioa> balorazioaErakutsi(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<service.Kotxea>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "kotxeakEskuratu", targetNamespace = "http://businessLogic/", className = "service.KotxeakEskuratu")
    @ResponseWrapper(localName = "kotxeakEskuratuResponse", targetNamespace = "http://businessLogic/", className = "service.KotxeakEskuratuResponse")
    @Action(input = "http://businessLogic/BLFacade/kotxeakEskuratuRequest", output = "http://businessLogic/BLFacade/kotxeakEskuratuResponse")
    public List<Kotxea> kotxeakEskuratu(
        @WebParam(name = "arg0", targetNamespace = "")
        Driver arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "balorazioaSortu", targetNamespace = "http://businessLogic/", className = "service.BalorazioaSortu")
    @ResponseWrapper(localName = "balorazioaSortuResponse", targetNamespace = "http://businessLogic/", className = "service.BalorazioaSortuResponse")
    @Action(input = "http://businessLogic/BLFacade/balorazioaSortuRequest", output = "http://businessLogic/BLFacade/balorazioaSortuResponse")
    public void balorazioaSortu(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        User arg3);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "erreklamazioaSortu", targetNamespace = "http://businessLogic/", className = "service.ErreklamazioaSortu")
    @ResponseWrapper(localName = "erreklamazioaSortuResponse", targetNamespace = "http://businessLogic/", className = "service.ErreklamazioaSortuResponse")
    @Action(input = "http://businessLogic/BLFacade/erreklamazioaSortuRequest", output = "http://businessLogic/BLFacade/erreklamazioaSortuResponse")
    public void erreklamazioaSortu(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Bidaiaria arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "erreserbaBaieztatu", targetNamespace = "http://businessLogic/", className = "service.ErreserbaBaieztatu")
    @ResponseWrapper(localName = "erreserbaBaieztatuResponse", targetNamespace = "http://businessLogic/", className = "service.ErreserbaBaieztatuResponse")
    @Action(input = "http://businessLogic/BLFacade/erreserbaBaieztatuRequest", output = "http://businessLogic/BLFacade/erreserbaBaieztatuResponse")
    public void erreserbaBaieztatu(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "bidaiKantzelatu", targetNamespace = "http://businessLogic/", className = "service.BidaiKantzelatu")
    @ResponseWrapper(localName = "bidaiKantzelatuResponse", targetNamespace = "http://businessLogic/", className = "service.BidaiKantzelatuResponse")
    @Action(input = "http://businessLogic/BLFacade/bidaiKantzelatuRequest", output = "http://businessLogic/BLFacade/bidaiKantzelatuResponse")
    public void bidaiKantzelatu(
        @WebParam(name = "arg0", targetNamespace = "")
        Driver arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns service.Kotxea
     * @throws KotxeaAlreadyExistException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "kotxeGehitu", targetNamespace = "http://businessLogic/", className = "service.KotxeGehitu")
    @ResponseWrapper(localName = "kotxeGehituResponse", targetNamespace = "http://businessLogic/", className = "service.KotxeGehituResponse")
    @Action(input = "http://businessLogic/BLFacade/kotxeGehituRequest", output = "http://businessLogic/BLFacade/kotxeGehituResponse", fault = {
        @FaultAction(className = KotxeaAlreadyExistException_Exception.class, value = "http://businessLogic/BLFacade/kotxeGehitu/Fault/KotxeaAlreadyExistException")
    })
    public Kotxea kotxeGehitu(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        Driver arg3)
        throws KotxeaAlreadyExistException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<service.Ride>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRidesByDriver", targetNamespace = "http://businessLogic/", className = "service.GetRidesByDriver")
    @ResponseWrapper(localName = "getRidesByDriverResponse", targetNamespace = "http://businessLogic/", className = "service.GetRidesByDriverResponse")
    @Action(input = "http://businessLogic/BLFacade/getRidesByDriverRequest", output = "http://businessLogic/BLFacade/getRidesByDriverResponse")
    public List<Ride> getRidesByDriver(
        @WebParam(name = "arg0", targetNamespace = "")
        Driver arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns service.Ride
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRide", targetNamespace = "http://businessLogic/", className = "service.GetRide")
    @ResponseWrapper(localName = "getRideResponse", targetNamespace = "http://businessLogic/", className = "service.GetRideResponse")
    @Action(input = "http://businessLogic/BLFacade/getRideRequest", output = "http://businessLogic/BLFacade/getRideResponse")
    public Ride getRide(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns service.Erreklamazioa
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "erreklamazioaLortu", targetNamespace = "http://businessLogic/", className = "service.ErreklamazioaLortu")
    @ResponseWrapper(localName = "erreklamazioaLortuResponse", targetNamespace = "http://businessLogic/", className = "service.ErreklamazioaLortuResponse")
    @Action(input = "http://businessLogic/BLFacade/erreklamazioaLortuRequest", output = "http://businessLogic/BLFacade/erreklamazioaLortuResponse")
    public Erreklamazioa erreklamazioaLortu(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<service.Mezua>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "mezuakLortu", targetNamespace = "http://businessLogic/", className = "service.MezuakLortu")
    @ResponseWrapper(localName = "mezuakLortuResponse", targetNamespace = "http://businessLogic/", className = "service.MezuakLortuResponse")
    @Action(input = "http://businessLogic/BLFacade/mezuakLortuRequest", output = "http://businessLogic/BLFacade/mezuakLortuResponse")
    public List<Mezua> mezuakLortu(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws AlertaAlreadyExistException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "alertaSortu", targetNamespace = "http://businessLogic/", className = "service.AlertaSortu")
    @ResponseWrapper(localName = "alertaSortuResponse", targetNamespace = "http://businessLogic/", className = "service.AlertaSortuResponse")
    @Action(input = "http://businessLogic/BLFacade/alertaSortuRequest", output = "http://businessLogic/BLFacade/alertaSortuResponse", fault = {
        @FaultAction(className = AlertaAlreadyExistException_Exception.class, value = "http://businessLogic/BLFacade/alertaSortu/Fault/AlertaAlreadyExistException")
    })
    public void alertaSortu(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        XMLGregorianCalendar arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        Bidaiaria arg3)
        throws AlertaAlreadyExistException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws ErreklamazioaEbatzitaException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "egoeraEzarri", targetNamespace = "http://businessLogic/", className = "service.EgoeraEzarri")
    @ResponseWrapper(localName = "egoeraEzarriResponse", targetNamespace = "http://businessLogic/", className = "service.EgoeraEzarriResponse")
    @Action(input = "http://businessLogic/BLFacade/egoeraEzarriRequest", output = "http://businessLogic/BLFacade/egoeraEzarriResponse", fault = {
        @FaultAction(className = ErreklamazioaEbatzitaException_Exception.class, value = "http://businessLogic/BLFacade/egoeraEzarri/Fault/erreklamazioaEbatzitaException")
    })
    public void egoeraEzarri(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws ErreklamazioaEbatzitaException_Exception
    ;

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "alertakEguneratu", targetNamespace = "http://businessLogic/", className = "service.AlertakEguneratu")
    @ResponseWrapper(localName = "alertakEguneratuResponse", targetNamespace = "http://businessLogic/", className = "service.AlertakEguneratuResponse")
    @Action(input = "http://businessLogic/BLFacade/alertakEguneratuRequest", output = "http://businessLogic/BLFacade/alertakEguneratuResponse")
    public void alertakEguneratu(
        @WebParam(name = "arg0", targetNamespace = "")
        Ride arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addMezua", targetNamespace = "http://businessLogic/", className = "service.AddMezua")
    @ResponseWrapper(localName = "addMezuaResponse", targetNamespace = "http://businessLogic/", className = "service.AddMezuaResponse")
    @Action(input = "http://businessLogic/BLFacade/addMezuaRequest", output = "http://businessLogic/BLFacade/addMezuaResponse")
    public void addMezua(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<service.Alerta>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "alertaIkusi", targetNamespace = "http://businessLogic/", className = "service.AlertaIkusi")
    @ResponseWrapper(localName = "alertaIkusiResponse", targetNamespace = "http://businessLogic/", className = "service.AlertaIkusiResponse")
    @Action(input = "http://businessLogic/BLFacade/alertaIkusiRequest", output = "http://businessLogic/BLFacade/alertaIkusiResponse")
    public List<Alerta> alertaIkusi(
        @WebParam(name = "arg0", targetNamespace = "")
        Bidaiaria arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "egoeraEzarriAdmin", targetNamespace = "http://businessLogic/", className = "service.EgoeraEzarriAdmin")
    @ResponseWrapper(localName = "egoeraEzarriAdminResponse", targetNamespace = "http://businessLogic/", className = "service.EgoeraEzarriAdminResponse")
    @Action(input = "http://businessLogic/BLFacade/egoeraEzarriAdminRequest", output = "http://businessLogic/BLFacade/egoeraEzarriAdminResponse")
    public void egoeraEzarriAdmin(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Admin arg2);

}
