
package service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "KotxeaAlreadyExistException", targetNamespace = "http://businessLogic/")
public class KotxeaAlreadyExistException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private KotxeaAlreadyExistException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public KotxeaAlreadyExistException_Exception(String message, KotxeaAlreadyExistException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public KotxeaAlreadyExistException_Exception(String message, KotxeaAlreadyExistException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: service.KotxeaAlreadyExistException
     */
    public KotxeaAlreadyExistException getFaultInfo() {
        return faultInfo;
    }

}
